version: "3.3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=zest
      - RABBITMQ_DEFAULT_PASS=iot

  # rabbit_all_ms_db:
  #   container_name: rabbit_all_ms_db
  #   image: mongo:4.1.12
  #   ports:
  #     - "27019:27017"
  #   environment:
  #     - MONGODB_DATABASE=rabbit_all_ms_db
  #   volumes:
  #     - /home/rsml/workspace/test_zastra/db:/data/db

networks:
  default:
    external: true
    name: zeppelin_microservices_network
